/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardUsersRouteImport } from './routes/dashboard/users'
import { Route as DashboardUserManualRouteImport } from './routes/dashboard/user-manual'
import { Route as DashboardTasksRouteImport } from './routes/dashboard/tasks'
import { Route as DashboardSystemDocsRouteImport } from './routes/dashboard/system-docs'
import { Route as DashboardSystemConfigRouteImport } from './routes/dashboard/system-config'
import { Route as DashboardServiceTicketsRouteImport } from './routes/dashboard/service-tickets'
import { Route as DashboardRolePermissionsRouteImport } from './routes/dashboard/role-permissions'
import { Route as DashboardReceivablesRouteImport } from './routes/dashboard/receivables'
import { Route as DashboardProfileRouteImport } from './routes/dashboard/profile'
import { Route as DashboardPaymentsRouteImport } from './routes/dashboard/payments'
import { Route as DashboardOpportunitiesRouteImport } from './routes/dashboard/opportunities'
import { Route as DashboardMenuManagementRouteImport } from './routes/dashboard/menu-management'
import { Route as DashboardLookupsRouteImport } from './routes/dashboard/lookups'
import { Route as DashboardIssueReportsRouteImport } from './routes/dashboard/issue-reports'
import { Route as DashboardInvoicesRouteImport } from './routes/dashboard/invoices'
import { Route as DashboardInvitationsRouteImport } from './routes/dashboard/invitations'
import { Route as DashboardFeatureRequestsRouteImport } from './routes/dashboard/feature-requests'
import { Route as DashboardErrorLogsRouteImport } from './routes/dashboard/error-logs'
import { Route as DashboardDevTodosRouteImport } from './routes/dashboard/dev-todos'
import { Route as DashboardDevHistoryRouteImport } from './routes/dashboard/dev-history'
import { Route as DashboardContractsRouteImport } from './routes/dashboard/contracts'
import { Route as DashboardAuditLogsRouteImport } from './routes/dashboard/audit-logs'
import { Route as DashboardActivityLogsRouteImport } from './routes/dashboard/activity-logs'
import { Route as DashboardLedgerIndexRouteImport } from './routes/dashboard/ledger/index'
import { Route as DashboardCasesIndexRouteImport } from './routes/dashboard/cases/index'
import { Route as DashboardLedgerSystemsRouteImport } from './routes/dashboard/ledger/systems'
import { Route as DashboardLedgerContractsRouteImport } from './routes/dashboard/ledger/contracts'
import { Route as DashboardLedgerClientsRouteImport } from './routes/dashboard/ledger/clients'
import { Route as DashboardClientsClientIdRouteImport } from './routes/dashboard/clients/$clientId'
import { Route as DashboardCasesCaseIdRouteImport } from './routes/dashboard/cases/$caseId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardUsersRoute = DashboardUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardUserManualRoute = DashboardUserManualRouteImport.update({
  id: '/user-manual',
  path: '/user-manual',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTasksRoute = DashboardTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSystemDocsRoute = DashboardSystemDocsRouteImport.update({
  id: '/system-docs',
  path: '/system-docs',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSystemConfigRoute = DashboardSystemConfigRouteImport.update({
  id: '/system-config',
  path: '/system-config',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardServiceTicketsRoute = DashboardServiceTicketsRouteImport.update({
  id: '/service-tickets',
  path: '/service-tickets',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardRolePermissionsRoute =
  DashboardRolePermissionsRouteImport.update({
    id: '/role-permissions',
    path: '/role-permissions',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardReceivablesRoute = DashboardReceivablesRouteImport.update({
  id: '/receivables',
  path: '/receivables',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPaymentsRoute = DashboardPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardOpportunitiesRoute = DashboardOpportunitiesRouteImport.update({
  id: '/opportunities',
  path: '/opportunities',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMenuManagementRoute = DashboardMenuManagementRouteImport.update({
  id: '/menu-management',
  path: '/menu-management',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLookupsRoute = DashboardLookupsRouteImport.update({
  id: '/lookups',
  path: '/lookups',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardIssueReportsRoute = DashboardIssueReportsRouteImport.update({
  id: '/issue-reports',
  path: '/issue-reports',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardInvoicesRoute = DashboardInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardInvitationsRoute = DashboardInvitationsRouteImport.update({
  id: '/invitations',
  path: '/invitations',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardFeatureRequestsRoute =
  DashboardFeatureRequestsRouteImport.update({
    id: '/feature-requests',
    path: '/feature-requests',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardErrorLogsRoute = DashboardErrorLogsRouteImport.update({
  id: '/error-logs',
  path: '/error-logs',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDevTodosRoute = DashboardDevTodosRouteImport.update({
  id: '/dev-todos',
  path: '/dev-todos',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDevHistoryRoute = DashboardDevHistoryRouteImport.update({
  id: '/dev-history',
  path: '/dev-history',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardContractsRoute = DashboardContractsRouteImport.update({
  id: '/contracts',
  path: '/contracts',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAuditLogsRoute = DashboardAuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardActivityLogsRoute = DashboardActivityLogsRouteImport.update({
  id: '/activity-logs',
  path: '/activity-logs',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLedgerIndexRoute = DashboardLedgerIndexRouteImport.update({
  id: '/ledger/',
  path: '/ledger/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCasesIndexRoute = DashboardCasesIndexRouteImport.update({
  id: '/cases/',
  path: '/cases/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLedgerSystemsRoute = DashboardLedgerSystemsRouteImport.update({
  id: '/ledger/systems',
  path: '/ledger/systems',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLedgerContractsRoute =
  DashboardLedgerContractsRouteImport.update({
    id: '/ledger/contracts',
    path: '/ledger/contracts',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardLedgerClientsRoute = DashboardLedgerClientsRouteImport.update({
  id: '/ledger/clients',
  path: '/ledger/clients',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardClientsClientIdRoute =
  DashboardClientsClientIdRouteImport.update({
    id: '/clients/$clientId',
    path: '/clients/$clientId',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardCasesCaseIdRoute = DashboardCasesCaseIdRouteImport.update({
  id: '/cases/$caseId',
  path: '/cases/$caseId',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard/activity-logs': typeof DashboardActivityLogsRoute
  '/dashboard/audit-logs': typeof DashboardAuditLogsRoute
  '/dashboard/contracts': typeof DashboardContractsRoute
  '/dashboard/dev-history': typeof DashboardDevHistoryRoute
  '/dashboard/dev-todos': typeof DashboardDevTodosRoute
  '/dashboard/error-logs': typeof DashboardErrorLogsRoute
  '/dashboard/feature-requests': typeof DashboardFeatureRequestsRoute
  '/dashboard/invitations': typeof DashboardInvitationsRoute
  '/dashboard/invoices': typeof DashboardInvoicesRoute
  '/dashboard/issue-reports': typeof DashboardIssueReportsRoute
  '/dashboard/lookups': typeof DashboardLookupsRoute
  '/dashboard/menu-management': typeof DashboardMenuManagementRoute
  '/dashboard/opportunities': typeof DashboardOpportunitiesRoute
  '/dashboard/payments': typeof DashboardPaymentsRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/receivables': typeof DashboardReceivablesRoute
  '/dashboard/role-permissions': typeof DashboardRolePermissionsRoute
  '/dashboard/service-tickets': typeof DashboardServiceTicketsRoute
  '/dashboard/system-config': typeof DashboardSystemConfigRoute
  '/dashboard/system-docs': typeof DashboardSystemDocsRoute
  '/dashboard/tasks': typeof DashboardTasksRoute
  '/dashboard/user-manual': typeof DashboardUserManualRoute
  '/dashboard/users': typeof DashboardUsersRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/cases/$caseId': typeof DashboardCasesCaseIdRoute
  '/dashboard/clients/$clientId': typeof DashboardClientsClientIdRoute
  '/dashboard/ledger/clients': typeof DashboardLedgerClientsRoute
  '/dashboard/ledger/contracts': typeof DashboardLedgerContractsRoute
  '/dashboard/ledger/systems': typeof DashboardLedgerSystemsRoute
  '/dashboard/cases/': typeof DashboardCasesIndexRoute
  '/dashboard/ledger/': typeof DashboardLedgerIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard/activity-logs': typeof DashboardActivityLogsRoute
  '/dashboard/audit-logs': typeof DashboardAuditLogsRoute
  '/dashboard/contracts': typeof DashboardContractsRoute
  '/dashboard/dev-history': typeof DashboardDevHistoryRoute
  '/dashboard/dev-todos': typeof DashboardDevTodosRoute
  '/dashboard/error-logs': typeof DashboardErrorLogsRoute
  '/dashboard/feature-requests': typeof DashboardFeatureRequestsRoute
  '/dashboard/invitations': typeof DashboardInvitationsRoute
  '/dashboard/invoices': typeof DashboardInvoicesRoute
  '/dashboard/issue-reports': typeof DashboardIssueReportsRoute
  '/dashboard/lookups': typeof DashboardLookupsRoute
  '/dashboard/menu-management': typeof DashboardMenuManagementRoute
  '/dashboard/opportunities': typeof DashboardOpportunitiesRoute
  '/dashboard/payments': typeof DashboardPaymentsRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/receivables': typeof DashboardReceivablesRoute
  '/dashboard/role-permissions': typeof DashboardRolePermissionsRoute
  '/dashboard/service-tickets': typeof DashboardServiceTicketsRoute
  '/dashboard/system-config': typeof DashboardSystemConfigRoute
  '/dashboard/system-docs': typeof DashboardSystemDocsRoute
  '/dashboard/tasks': typeof DashboardTasksRoute
  '/dashboard/user-manual': typeof DashboardUserManualRoute
  '/dashboard/users': typeof DashboardUsersRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/cases/$caseId': typeof DashboardCasesCaseIdRoute
  '/dashboard/clients/$clientId': typeof DashboardClientsClientIdRoute
  '/dashboard/ledger/clients': typeof DashboardLedgerClientsRoute
  '/dashboard/ledger/contracts': typeof DashboardLedgerContractsRoute
  '/dashboard/ledger/systems': typeof DashboardLedgerSystemsRoute
  '/dashboard/cases': typeof DashboardCasesIndexRoute
  '/dashboard/ledger': typeof DashboardLedgerIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard/activity-logs': typeof DashboardActivityLogsRoute
  '/dashboard/audit-logs': typeof DashboardAuditLogsRoute
  '/dashboard/contracts': typeof DashboardContractsRoute
  '/dashboard/dev-history': typeof DashboardDevHistoryRoute
  '/dashboard/dev-todos': typeof DashboardDevTodosRoute
  '/dashboard/error-logs': typeof DashboardErrorLogsRoute
  '/dashboard/feature-requests': typeof DashboardFeatureRequestsRoute
  '/dashboard/invitations': typeof DashboardInvitationsRoute
  '/dashboard/invoices': typeof DashboardInvoicesRoute
  '/dashboard/issue-reports': typeof DashboardIssueReportsRoute
  '/dashboard/lookups': typeof DashboardLookupsRoute
  '/dashboard/menu-management': typeof DashboardMenuManagementRoute
  '/dashboard/opportunities': typeof DashboardOpportunitiesRoute
  '/dashboard/payments': typeof DashboardPaymentsRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/receivables': typeof DashboardReceivablesRoute
  '/dashboard/role-permissions': typeof DashboardRolePermissionsRoute
  '/dashboard/service-tickets': typeof DashboardServiceTicketsRoute
  '/dashboard/system-config': typeof DashboardSystemConfigRoute
  '/dashboard/system-docs': typeof DashboardSystemDocsRoute
  '/dashboard/tasks': typeof DashboardTasksRoute
  '/dashboard/user-manual': typeof DashboardUserManualRoute
  '/dashboard/users': typeof DashboardUsersRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/cases/$caseId': typeof DashboardCasesCaseIdRoute
  '/dashboard/clients/$clientId': typeof DashboardClientsClientIdRoute
  '/dashboard/ledger/clients': typeof DashboardLedgerClientsRoute
  '/dashboard/ledger/contracts': typeof DashboardLedgerContractsRoute
  '/dashboard/ledger/systems': typeof DashboardLedgerSystemsRoute
  '/dashboard/cases/': typeof DashboardCasesIndexRoute
  '/dashboard/ledger/': typeof DashboardLedgerIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/dashboard/activity-logs'
    | '/dashboard/audit-logs'
    | '/dashboard/contracts'
    | '/dashboard/dev-history'
    | '/dashboard/dev-todos'
    | '/dashboard/error-logs'
    | '/dashboard/feature-requests'
    | '/dashboard/invitations'
    | '/dashboard/invoices'
    | '/dashboard/issue-reports'
    | '/dashboard/lookups'
    | '/dashboard/menu-management'
    | '/dashboard/opportunities'
    | '/dashboard/payments'
    | '/dashboard/profile'
    | '/dashboard/receivables'
    | '/dashboard/role-permissions'
    | '/dashboard/service-tickets'
    | '/dashboard/system-config'
    | '/dashboard/system-docs'
    | '/dashboard/tasks'
    | '/dashboard/user-manual'
    | '/dashboard/users'
    | '/dashboard/'
    | '/dashboard/cases/$caseId'
    | '/dashboard/clients/$clientId'
    | '/dashboard/ledger/clients'
    | '/dashboard/ledger/contracts'
    | '/dashboard/ledger/systems'
    | '/dashboard/cases/'
    | '/dashboard/ledger/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard/activity-logs'
    | '/dashboard/audit-logs'
    | '/dashboard/contracts'
    | '/dashboard/dev-history'
    | '/dashboard/dev-todos'
    | '/dashboard/error-logs'
    | '/dashboard/feature-requests'
    | '/dashboard/invitations'
    | '/dashboard/invoices'
    | '/dashboard/issue-reports'
    | '/dashboard/lookups'
    | '/dashboard/menu-management'
    | '/dashboard/opportunities'
    | '/dashboard/payments'
    | '/dashboard/profile'
    | '/dashboard/receivables'
    | '/dashboard/role-permissions'
    | '/dashboard/service-tickets'
    | '/dashboard/system-config'
    | '/dashboard/system-docs'
    | '/dashboard/tasks'
    | '/dashboard/user-manual'
    | '/dashboard/users'
    | '/dashboard'
    | '/dashboard/cases/$caseId'
    | '/dashboard/clients/$clientId'
    | '/dashboard/ledger/clients'
    | '/dashboard/ledger/contracts'
    | '/dashboard/ledger/systems'
    | '/dashboard/cases'
    | '/dashboard/ledger'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/dashboard/activity-logs'
    | '/dashboard/audit-logs'
    | '/dashboard/contracts'
    | '/dashboard/dev-history'
    | '/dashboard/dev-todos'
    | '/dashboard/error-logs'
    | '/dashboard/feature-requests'
    | '/dashboard/invitations'
    | '/dashboard/invoices'
    | '/dashboard/issue-reports'
    | '/dashboard/lookups'
    | '/dashboard/menu-management'
    | '/dashboard/opportunities'
    | '/dashboard/payments'
    | '/dashboard/profile'
    | '/dashboard/receivables'
    | '/dashboard/role-permissions'
    | '/dashboard/service-tickets'
    | '/dashboard/system-config'
    | '/dashboard/system-docs'
    | '/dashboard/tasks'
    | '/dashboard/user-manual'
    | '/dashboard/users'
    | '/dashboard/'
    | '/dashboard/cases/$caseId'
    | '/dashboard/clients/$clientId'
    | '/dashboard/ledger/clients'
    | '/dashboard/ledger/contracts'
    | '/dashboard/ledger/systems'
    | '/dashboard/cases/'
    | '/dashboard/ledger/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/users': {
      id: '/dashboard/users'
      path: '/users'
      fullPath: '/dashboard/users'
      preLoaderRoute: typeof DashboardUsersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/user-manual': {
      id: '/dashboard/user-manual'
      path: '/user-manual'
      fullPath: '/dashboard/user-manual'
      preLoaderRoute: typeof DashboardUserManualRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/tasks': {
      id: '/dashboard/tasks'
      path: '/tasks'
      fullPath: '/dashboard/tasks'
      preLoaderRoute: typeof DashboardTasksRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/system-docs': {
      id: '/dashboard/system-docs'
      path: '/system-docs'
      fullPath: '/dashboard/system-docs'
      preLoaderRoute: typeof DashboardSystemDocsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/system-config': {
      id: '/dashboard/system-config'
      path: '/system-config'
      fullPath: '/dashboard/system-config'
      preLoaderRoute: typeof DashboardSystemConfigRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/service-tickets': {
      id: '/dashboard/service-tickets'
      path: '/service-tickets'
      fullPath: '/dashboard/service-tickets'
      preLoaderRoute: typeof DashboardServiceTicketsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/role-permissions': {
      id: '/dashboard/role-permissions'
      path: '/role-permissions'
      fullPath: '/dashboard/role-permissions'
      preLoaderRoute: typeof DashboardRolePermissionsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/receivables': {
      id: '/dashboard/receivables'
      path: '/receivables'
      fullPath: '/dashboard/receivables'
      preLoaderRoute: typeof DashboardReceivablesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/profile': {
      id: '/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/payments': {
      id: '/dashboard/payments'
      path: '/payments'
      fullPath: '/dashboard/payments'
      preLoaderRoute: typeof DashboardPaymentsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/opportunities': {
      id: '/dashboard/opportunities'
      path: '/opportunities'
      fullPath: '/dashboard/opportunities'
      preLoaderRoute: typeof DashboardOpportunitiesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/menu-management': {
      id: '/dashboard/menu-management'
      path: '/menu-management'
      fullPath: '/dashboard/menu-management'
      preLoaderRoute: typeof DashboardMenuManagementRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/lookups': {
      id: '/dashboard/lookups'
      path: '/lookups'
      fullPath: '/dashboard/lookups'
      preLoaderRoute: typeof DashboardLookupsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/issue-reports': {
      id: '/dashboard/issue-reports'
      path: '/issue-reports'
      fullPath: '/dashboard/issue-reports'
      preLoaderRoute: typeof DashboardIssueReportsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/invoices': {
      id: '/dashboard/invoices'
      path: '/invoices'
      fullPath: '/dashboard/invoices'
      preLoaderRoute: typeof DashboardInvoicesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/invitations': {
      id: '/dashboard/invitations'
      path: '/invitations'
      fullPath: '/dashboard/invitations'
      preLoaderRoute: typeof DashboardInvitationsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/feature-requests': {
      id: '/dashboard/feature-requests'
      path: '/feature-requests'
      fullPath: '/dashboard/feature-requests'
      preLoaderRoute: typeof DashboardFeatureRequestsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/error-logs': {
      id: '/dashboard/error-logs'
      path: '/error-logs'
      fullPath: '/dashboard/error-logs'
      preLoaderRoute: typeof DashboardErrorLogsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/dev-todos': {
      id: '/dashboard/dev-todos'
      path: '/dev-todos'
      fullPath: '/dashboard/dev-todos'
      preLoaderRoute: typeof DashboardDevTodosRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/dev-history': {
      id: '/dashboard/dev-history'
      path: '/dev-history'
      fullPath: '/dashboard/dev-history'
      preLoaderRoute: typeof DashboardDevHistoryRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/contracts': {
      id: '/dashboard/contracts'
      path: '/contracts'
      fullPath: '/dashboard/contracts'
      preLoaderRoute: typeof DashboardContractsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/audit-logs': {
      id: '/dashboard/audit-logs'
      path: '/audit-logs'
      fullPath: '/dashboard/audit-logs'
      preLoaderRoute: typeof DashboardAuditLogsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/activity-logs': {
      id: '/dashboard/activity-logs'
      path: '/activity-logs'
      fullPath: '/dashboard/activity-logs'
      preLoaderRoute: typeof DashboardActivityLogsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/ledger/': {
      id: '/dashboard/ledger/'
      path: '/ledger'
      fullPath: '/dashboard/ledger/'
      preLoaderRoute: typeof DashboardLedgerIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/cases/': {
      id: '/dashboard/cases/'
      path: '/cases'
      fullPath: '/dashboard/cases/'
      preLoaderRoute: typeof DashboardCasesIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/ledger/systems': {
      id: '/dashboard/ledger/systems'
      path: '/ledger/systems'
      fullPath: '/dashboard/ledger/systems'
      preLoaderRoute: typeof DashboardLedgerSystemsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/ledger/contracts': {
      id: '/dashboard/ledger/contracts'
      path: '/ledger/contracts'
      fullPath: '/dashboard/ledger/contracts'
      preLoaderRoute: typeof DashboardLedgerContractsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/ledger/clients': {
      id: '/dashboard/ledger/clients'
      path: '/ledger/clients'
      fullPath: '/dashboard/ledger/clients'
      preLoaderRoute: typeof DashboardLedgerClientsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/clients/$clientId': {
      id: '/dashboard/clients/$clientId'
      path: '/clients/$clientId'
      fullPath: '/dashboard/clients/$clientId'
      preLoaderRoute: typeof DashboardClientsClientIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/cases/$caseId': {
      id: '/dashboard/cases/$caseId'
      path: '/cases/$caseId'
      fullPath: '/dashboard/cases/$caseId'
      preLoaderRoute: typeof DashboardCasesCaseIdRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardActivityLogsRoute: typeof DashboardActivityLogsRoute
  DashboardAuditLogsRoute: typeof DashboardAuditLogsRoute
  DashboardContractsRoute: typeof DashboardContractsRoute
  DashboardDevHistoryRoute: typeof DashboardDevHistoryRoute
  DashboardDevTodosRoute: typeof DashboardDevTodosRoute
  DashboardErrorLogsRoute: typeof DashboardErrorLogsRoute
  DashboardFeatureRequestsRoute: typeof DashboardFeatureRequestsRoute
  DashboardInvitationsRoute: typeof DashboardInvitationsRoute
  DashboardInvoicesRoute: typeof DashboardInvoicesRoute
  DashboardIssueReportsRoute: typeof DashboardIssueReportsRoute
  DashboardLookupsRoute: typeof DashboardLookupsRoute
  DashboardMenuManagementRoute: typeof DashboardMenuManagementRoute
  DashboardOpportunitiesRoute: typeof DashboardOpportunitiesRoute
  DashboardPaymentsRoute: typeof DashboardPaymentsRoute
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardReceivablesRoute: typeof DashboardReceivablesRoute
  DashboardRolePermissionsRoute: typeof DashboardRolePermissionsRoute
  DashboardServiceTicketsRoute: typeof DashboardServiceTicketsRoute
  DashboardSystemConfigRoute: typeof DashboardSystemConfigRoute
  DashboardSystemDocsRoute: typeof DashboardSystemDocsRoute
  DashboardTasksRoute: typeof DashboardTasksRoute
  DashboardUserManualRoute: typeof DashboardUserManualRoute
  DashboardUsersRoute: typeof DashboardUsersRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardCasesCaseIdRoute: typeof DashboardCasesCaseIdRoute
  DashboardClientsClientIdRoute: typeof DashboardClientsClientIdRoute
  DashboardLedgerClientsRoute: typeof DashboardLedgerClientsRoute
  DashboardLedgerContractsRoute: typeof DashboardLedgerContractsRoute
  DashboardLedgerSystemsRoute: typeof DashboardLedgerSystemsRoute
  DashboardCasesIndexRoute: typeof DashboardCasesIndexRoute
  DashboardLedgerIndexRoute: typeof DashboardLedgerIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardActivityLogsRoute: DashboardActivityLogsRoute,
  DashboardAuditLogsRoute: DashboardAuditLogsRoute,
  DashboardContractsRoute: DashboardContractsRoute,
  DashboardDevHistoryRoute: DashboardDevHistoryRoute,
  DashboardDevTodosRoute: DashboardDevTodosRoute,
  DashboardErrorLogsRoute: DashboardErrorLogsRoute,
  DashboardFeatureRequestsRoute: DashboardFeatureRequestsRoute,
  DashboardInvitationsRoute: DashboardInvitationsRoute,
  DashboardInvoicesRoute: DashboardInvoicesRoute,
  DashboardIssueReportsRoute: DashboardIssueReportsRoute,
  DashboardLookupsRoute: DashboardLookupsRoute,
  DashboardMenuManagementRoute: DashboardMenuManagementRoute,
  DashboardOpportunitiesRoute: DashboardOpportunitiesRoute,
  DashboardPaymentsRoute: DashboardPaymentsRoute,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardReceivablesRoute: DashboardReceivablesRoute,
  DashboardRolePermissionsRoute: DashboardRolePermissionsRoute,
  DashboardServiceTicketsRoute: DashboardServiceTicketsRoute,
  DashboardSystemConfigRoute: DashboardSystemConfigRoute,
  DashboardSystemDocsRoute: DashboardSystemDocsRoute,
  DashboardTasksRoute: DashboardTasksRoute,
  DashboardUserManualRoute: DashboardUserManualRoute,
  DashboardUsersRoute: DashboardUsersRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardCasesCaseIdRoute: DashboardCasesCaseIdRoute,
  DashboardClientsClientIdRoute: DashboardClientsClientIdRoute,
  DashboardLedgerClientsRoute: DashboardLedgerClientsRoute,
  DashboardLedgerContractsRoute: DashboardLedgerContractsRoute,
  DashboardLedgerSystemsRoute: DashboardLedgerSystemsRoute,
  DashboardCasesIndexRoute: DashboardCasesIndexRoute,
  DashboardLedgerIndexRoute: DashboardLedgerIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
