/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardWorkspaceRouteImport } from './routes/dashboard/workspace'
import { Route as DashboardUsersRouteImport } from './routes/dashboard/users'
import { Route as DashboardUserManualRouteImport } from './routes/dashboard/user-manual'
import { Route as DashboardTasksRouteImport } from './routes/dashboard/tasks'
import { Route as DashboardSystemDocsRouteImport } from './routes/dashboard/system-docs'
import { Route as DashboardSystemConfigRouteImport } from './routes/dashboard/system-config'
import { Route as DashboardServiceTicketsRouteImport } from './routes/dashboard/service-tickets'
import { Route as DashboardRolePermissionsRouteImport } from './routes/dashboard/role-permissions'
import { Route as DashboardReportsRouteImport } from './routes/dashboard/reports'
import { Route as DashboardRenewalsRouteImport } from './routes/dashboard/renewals'
import { Route as DashboardReceivablesRouteImport } from './routes/dashboard/receivables'
import { Route as DashboardQuotesRouteImport } from './routes/dashboard/quotes'
import { Route as DashboardProjectDashboardRouteImport } from './routes/dashboard/project-dashboard'
import { Route as DashboardProjectBoardRouteImport } from './routes/dashboard/project-board'
import { Route as DashboardProfileRouteImport } from './routes/dashboard/profile'
import { Route as DashboardPaymentsRouteImport } from './routes/dashboard/payments'
import { Route as DashboardOpportunitiesRouteImport } from './routes/dashboard/opportunities'
import { Route as DashboardMenuManagementRouteImport } from './routes/dashboard/menu-management'
import { Route as DashboardMembersRouteImport } from './routes/dashboard/members'
import { Route as DashboardLookupsRouteImport } from './routes/dashboard/lookups'
import { Route as DashboardIssueReportsRouteImport } from './routes/dashboard/issue-reports'
import { Route as DashboardInvoicesRouteImport } from './routes/dashboard/invoices'
import { Route as DashboardInvitationsRouteImport } from './routes/dashboard/invitations'
import { Route as DashboardFundRouteImport } from './routes/dashboard/fund'
import { Route as DashboardFeatureRequestsRouteImport } from './routes/dashboard/feature-requests'
import { Route as DashboardErrorLogsRouteImport } from './routes/dashboard/error-logs'
import { Route as DashboardDevTodosRouteImport } from './routes/dashboard/dev-todos'
import { Route as DashboardDevHistoryRouteImport } from './routes/dashboard/dev-history'
import { Route as DashboardContractsRouteImport } from './routes/dashboard/contracts'
import { Route as DashboardCommissionsRouteImport } from './routes/dashboard/commissions'
import { Route as DashboardCalendarRouteImport } from './routes/dashboard/calendar'
import { Route as DashboardAuditLogsRouteImport } from './routes/dashboard/audit-logs'
import { Route as DashboardAiKnowledgeRouteImport } from './routes/dashboard/ai-knowledge'
import { Route as DashboardAiAgentsRouteImport } from './routes/dashboard/ai-agents'
import { Route as DashboardAgentTokensRouteImport } from './routes/dashboard/agent-tokens'
import { Route as DashboardAgentScopesRouteImport } from './routes/dashboard/agent-scopes'
import { Route as DashboardAgentPromptRouteImport } from './routes/dashboard/agent-prompt'
import { Route as DashboardAgentAuditRouteImport } from './routes/dashboard/agent-audit'
import { Route as DashboardAgentActivityRouteImport } from './routes/dashboard/agent-activity'
import { Route as DashboardActivityLogsRouteImport } from './routes/dashboard/activity-logs'
import { Route as DashboardLedgerIndexRouteImport } from './routes/dashboard/ledger/index'
import { Route as DashboardCasesIndexRouteImport } from './routes/dashboard/cases/index'
import { Route as DashboardLedgerSystemsRouteImport } from './routes/dashboard/ledger/systems'
import { Route as DashboardLedgerContractsRouteImport } from './routes/dashboard/ledger/contracts'
import { Route as DashboardLedgerClientsRouteImport } from './routes/dashboard/ledger/clients'
import { Route as DashboardClientsClientIdRouteImport } from './routes/dashboard/clients/$clientId'
import { Route as DashboardCasesCaseIdRouteImport } from './routes/dashboard/cases/$caseId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardWorkspaceRoute = DashboardWorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardUsersRoute = DashboardUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardUserManualRoute = DashboardUserManualRouteImport.update({
  id: '/user-manual',
  path: '/user-manual',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTasksRoute = DashboardTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSystemDocsRoute = DashboardSystemDocsRouteImport.update({
  id: '/system-docs',
  path: '/system-docs',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSystemConfigRoute = DashboardSystemConfigRouteImport.update({
  id: '/system-config',
  path: '/system-config',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardServiceTicketsRoute = DashboardServiceTicketsRouteImport.update({
  id: '/service-tickets',
  path: '/service-tickets',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardRolePermissionsRoute =
  DashboardRolePermissionsRouteImport.update({
    id: '/role-permissions',
    path: '/role-permissions',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardReportsRoute = DashboardReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardRenewalsRoute = DashboardRenewalsRouteImport.update({
  id: '/renewals',
  path: '/renewals',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardReceivablesRoute = DashboardReceivablesRouteImport.update({
  id: '/receivables',
  path: '/receivables',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardQuotesRoute = DashboardQuotesRouteImport.update({
  id: '/quotes',
  path: '/quotes',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProjectDashboardRoute =
  DashboardProjectDashboardRouteImport.update({
    id: '/project-dashboard',
    path: '/project-dashboard',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardProjectBoardRoute = DashboardProjectBoardRouteImport.update({
  id: '/project-board',
  path: '/project-board',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPaymentsRoute = DashboardPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardOpportunitiesRoute = DashboardOpportunitiesRouteImport.update({
  id: '/opportunities',
  path: '/opportunities',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMenuManagementRoute = DashboardMenuManagementRouteImport.update({
  id: '/menu-management',
  path: '/menu-management',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMembersRoute = DashboardMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLookupsRoute = DashboardLookupsRouteImport.update({
  id: '/lookups',
  path: '/lookups',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardIssueReportsRoute = DashboardIssueReportsRouteImport.update({
  id: '/issue-reports',
  path: '/issue-reports',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardInvoicesRoute = DashboardInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardInvitationsRoute = DashboardInvitationsRouteImport.update({
  id: '/invitations',
  path: '/invitations',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardFundRoute = DashboardFundRouteImport.update({
  id: '/fund',
  path: '/fund',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardFeatureRequestsRoute =
  DashboardFeatureRequestsRouteImport.update({
    id: '/feature-requests',
    path: '/feature-requests',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardErrorLogsRoute = DashboardErrorLogsRouteImport.update({
  id: '/error-logs',
  path: '/error-logs',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDevTodosRoute = DashboardDevTodosRouteImport.update({
  id: '/dev-todos',
  path: '/dev-todos',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDevHistoryRoute = DashboardDevHistoryRouteImport.update({
  id: '/dev-history',
  path: '/dev-history',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardContractsRoute = DashboardContractsRouteImport.update({
  id: '/contracts',
  path: '/contracts',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCommissionsRoute = DashboardCommissionsRouteImport.update({
  id: '/commissions',
  path: '/commissions',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCalendarRoute = DashboardCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAuditLogsRoute = DashboardAuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAiKnowledgeRoute = DashboardAiKnowledgeRouteImport.update({
  id: '/ai-knowledge',
  path: '/ai-knowledge',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAiAgentsRoute = DashboardAiAgentsRouteImport.update({
  id: '/ai-agents',
  path: '/ai-agents',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAgentTokensRoute = DashboardAgentTokensRouteImport.update({
  id: '/agent-tokens',
  path: '/agent-tokens',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAgentScopesRoute = DashboardAgentScopesRouteImport.update({
  id: '/agent-scopes',
  path: '/agent-scopes',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAgentPromptRoute = DashboardAgentPromptRouteImport.update({
  id: '/agent-prompt',
  path: '/agent-prompt',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAgentAuditRoute = DashboardAgentAuditRouteImport.update({
  id: '/agent-audit',
  path: '/agent-audit',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAgentActivityRoute = DashboardAgentActivityRouteImport.update({
  id: '/agent-activity',
  path: '/agent-activity',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardActivityLogsRoute = DashboardActivityLogsRouteImport.update({
  id: '/activity-logs',
  path: '/activity-logs',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLedgerIndexRoute = DashboardLedgerIndexRouteImport.update({
  id: '/ledger/',
  path: '/ledger/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCasesIndexRoute = DashboardCasesIndexRouteImport.update({
  id: '/cases/',
  path: '/cases/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLedgerSystemsRoute = DashboardLedgerSystemsRouteImport.update({
  id: '/ledger/systems',
  path: '/ledger/systems',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLedgerContractsRoute =
  DashboardLedgerContractsRouteImport.update({
    id: '/ledger/contracts',
    path: '/ledger/contracts',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardLedgerClientsRoute = DashboardLedgerClientsRouteImport.update({
  id: '/ledger/clients',
  path: '/ledger/clients',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardClientsClientIdRoute =
  DashboardClientsClientIdRouteImport.update({
    id: '/clients/$clientId',
    path: '/clients/$clientId',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardCasesCaseIdRoute = DashboardCasesCaseIdRouteImport.update({
  id: '/cases/$caseId',
  path: '/cases/$caseId',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard/activity-logs': typeof DashboardActivityLogsRoute
  '/dashboard/agent-activity': typeof DashboardAgentActivityRoute
  '/dashboard/agent-audit': typeof DashboardAgentAuditRoute
  '/dashboard/agent-prompt': typeof DashboardAgentPromptRoute
  '/dashboard/agent-scopes': typeof DashboardAgentScopesRoute
  '/dashboard/agent-tokens': typeof DashboardAgentTokensRoute
  '/dashboard/ai-agents': typeof DashboardAiAgentsRoute
  '/dashboard/ai-knowledge': typeof DashboardAiKnowledgeRoute
  '/dashboard/audit-logs': typeof DashboardAuditLogsRoute
  '/dashboard/calendar': typeof DashboardCalendarRoute
  '/dashboard/commissions': typeof DashboardCommissionsRoute
  '/dashboard/contracts': typeof DashboardContractsRoute
  '/dashboard/dev-history': typeof DashboardDevHistoryRoute
  '/dashboard/dev-todos': typeof DashboardDevTodosRoute
  '/dashboard/error-logs': typeof DashboardErrorLogsRoute
  '/dashboard/feature-requests': typeof DashboardFeatureRequestsRoute
  '/dashboard/fund': typeof DashboardFundRoute
  '/dashboard/invitations': typeof DashboardInvitationsRoute
  '/dashboard/invoices': typeof DashboardInvoicesRoute
  '/dashboard/issue-reports': typeof DashboardIssueReportsRoute
  '/dashboard/lookups': typeof DashboardLookupsRoute
  '/dashboard/members': typeof DashboardMembersRoute
  '/dashboard/menu-management': typeof DashboardMenuManagementRoute
  '/dashboard/opportunities': typeof DashboardOpportunitiesRoute
  '/dashboard/payments': typeof DashboardPaymentsRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/project-board': typeof DashboardProjectBoardRoute
  '/dashboard/project-dashboard': typeof DashboardProjectDashboardRoute
  '/dashboard/quotes': typeof DashboardQuotesRoute
  '/dashboard/receivables': typeof DashboardReceivablesRoute
  '/dashboard/renewals': typeof DashboardRenewalsRoute
  '/dashboard/reports': typeof DashboardReportsRoute
  '/dashboard/role-permissions': typeof DashboardRolePermissionsRoute
  '/dashboard/service-tickets': typeof DashboardServiceTicketsRoute
  '/dashboard/system-config': typeof DashboardSystemConfigRoute
  '/dashboard/system-docs': typeof DashboardSystemDocsRoute
  '/dashboard/tasks': typeof DashboardTasksRoute
  '/dashboard/user-manual': typeof DashboardUserManualRoute
  '/dashboard/users': typeof DashboardUsersRoute
  '/dashboard/workspace': typeof DashboardWorkspaceRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/cases/$caseId': typeof DashboardCasesCaseIdRoute
  '/dashboard/clients/$clientId': typeof DashboardClientsClientIdRoute
  '/dashboard/ledger/clients': typeof DashboardLedgerClientsRoute
  '/dashboard/ledger/contracts': typeof DashboardLedgerContractsRoute
  '/dashboard/ledger/systems': typeof DashboardLedgerSystemsRoute
  '/dashboard/cases/': typeof DashboardCasesIndexRoute
  '/dashboard/ledger/': typeof DashboardLedgerIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard/activity-logs': typeof DashboardActivityLogsRoute
  '/dashboard/agent-activity': typeof DashboardAgentActivityRoute
  '/dashboard/agent-audit': typeof DashboardAgentAuditRoute
  '/dashboard/agent-prompt': typeof DashboardAgentPromptRoute
  '/dashboard/agent-scopes': typeof DashboardAgentScopesRoute
  '/dashboard/agent-tokens': typeof DashboardAgentTokensRoute
  '/dashboard/ai-agents': typeof DashboardAiAgentsRoute
  '/dashboard/ai-knowledge': typeof DashboardAiKnowledgeRoute
  '/dashboard/audit-logs': typeof DashboardAuditLogsRoute
  '/dashboard/calendar': typeof DashboardCalendarRoute
  '/dashboard/commissions': typeof DashboardCommissionsRoute
  '/dashboard/contracts': typeof DashboardContractsRoute
  '/dashboard/dev-history': typeof DashboardDevHistoryRoute
  '/dashboard/dev-todos': typeof DashboardDevTodosRoute
  '/dashboard/error-logs': typeof DashboardErrorLogsRoute
  '/dashboard/feature-requests': typeof DashboardFeatureRequestsRoute
  '/dashboard/fund': typeof DashboardFundRoute
  '/dashboard/invitations': typeof DashboardInvitationsRoute
  '/dashboard/invoices': typeof DashboardInvoicesRoute
  '/dashboard/issue-reports': typeof DashboardIssueReportsRoute
  '/dashboard/lookups': typeof DashboardLookupsRoute
  '/dashboard/members': typeof DashboardMembersRoute
  '/dashboard/menu-management': typeof DashboardMenuManagementRoute
  '/dashboard/opportunities': typeof DashboardOpportunitiesRoute
  '/dashboard/payments': typeof DashboardPaymentsRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/project-board': typeof DashboardProjectBoardRoute
  '/dashboard/project-dashboard': typeof DashboardProjectDashboardRoute
  '/dashboard/quotes': typeof DashboardQuotesRoute
  '/dashboard/receivables': typeof DashboardReceivablesRoute
  '/dashboard/renewals': typeof DashboardRenewalsRoute
  '/dashboard/reports': typeof DashboardReportsRoute
  '/dashboard/role-permissions': typeof DashboardRolePermissionsRoute
  '/dashboard/service-tickets': typeof DashboardServiceTicketsRoute
  '/dashboard/system-config': typeof DashboardSystemConfigRoute
  '/dashboard/system-docs': typeof DashboardSystemDocsRoute
  '/dashboard/tasks': typeof DashboardTasksRoute
  '/dashboard/user-manual': typeof DashboardUserManualRoute
  '/dashboard/users': typeof DashboardUsersRoute
  '/dashboard/workspace': typeof DashboardWorkspaceRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/cases/$caseId': typeof DashboardCasesCaseIdRoute
  '/dashboard/clients/$clientId': typeof DashboardClientsClientIdRoute
  '/dashboard/ledger/clients': typeof DashboardLedgerClientsRoute
  '/dashboard/ledger/contracts': typeof DashboardLedgerContractsRoute
  '/dashboard/ledger/systems': typeof DashboardLedgerSystemsRoute
  '/dashboard/cases': typeof DashboardCasesIndexRoute
  '/dashboard/ledger': typeof DashboardLedgerIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard/activity-logs': typeof DashboardActivityLogsRoute
  '/dashboard/agent-activity': typeof DashboardAgentActivityRoute
  '/dashboard/agent-audit': typeof DashboardAgentAuditRoute
  '/dashboard/agent-prompt': typeof DashboardAgentPromptRoute
  '/dashboard/agent-scopes': typeof DashboardAgentScopesRoute
  '/dashboard/agent-tokens': typeof DashboardAgentTokensRoute
  '/dashboard/ai-agents': typeof DashboardAiAgentsRoute
  '/dashboard/ai-knowledge': typeof DashboardAiKnowledgeRoute
  '/dashboard/audit-logs': typeof DashboardAuditLogsRoute
  '/dashboard/calendar': typeof DashboardCalendarRoute
  '/dashboard/commissions': typeof DashboardCommissionsRoute
  '/dashboard/contracts': typeof DashboardContractsRoute
  '/dashboard/dev-history': typeof DashboardDevHistoryRoute
  '/dashboard/dev-todos': typeof DashboardDevTodosRoute
  '/dashboard/error-logs': typeof DashboardErrorLogsRoute
  '/dashboard/feature-requests': typeof DashboardFeatureRequestsRoute
  '/dashboard/fund': typeof DashboardFundRoute
  '/dashboard/invitations': typeof DashboardInvitationsRoute
  '/dashboard/invoices': typeof DashboardInvoicesRoute
  '/dashboard/issue-reports': typeof DashboardIssueReportsRoute
  '/dashboard/lookups': typeof DashboardLookupsRoute
  '/dashboard/members': typeof DashboardMembersRoute
  '/dashboard/menu-management': typeof DashboardMenuManagementRoute
  '/dashboard/opportunities': typeof DashboardOpportunitiesRoute
  '/dashboard/payments': typeof DashboardPaymentsRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/project-board': typeof DashboardProjectBoardRoute
  '/dashboard/project-dashboard': typeof DashboardProjectDashboardRoute
  '/dashboard/quotes': typeof DashboardQuotesRoute
  '/dashboard/receivables': typeof DashboardReceivablesRoute
  '/dashboard/renewals': typeof DashboardRenewalsRoute
  '/dashboard/reports': typeof DashboardReportsRoute
  '/dashboard/role-permissions': typeof DashboardRolePermissionsRoute
  '/dashboard/service-tickets': typeof DashboardServiceTicketsRoute
  '/dashboard/system-config': typeof DashboardSystemConfigRoute
  '/dashboard/system-docs': typeof DashboardSystemDocsRoute
  '/dashboard/tasks': typeof DashboardTasksRoute
  '/dashboard/user-manual': typeof DashboardUserManualRoute
  '/dashboard/users': typeof DashboardUsersRoute
  '/dashboard/workspace': typeof DashboardWorkspaceRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/cases/$caseId': typeof DashboardCasesCaseIdRoute
  '/dashboard/clients/$clientId': typeof DashboardClientsClientIdRoute
  '/dashboard/ledger/clients': typeof DashboardLedgerClientsRoute
  '/dashboard/ledger/contracts': typeof DashboardLedgerContractsRoute
  '/dashboard/ledger/systems': typeof DashboardLedgerSystemsRoute
  '/dashboard/cases/': typeof DashboardCasesIndexRoute
  '/dashboard/ledger/': typeof DashboardLedgerIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/dashboard/activity-logs'
    | '/dashboard/agent-activity'
    | '/dashboard/agent-audit'
    | '/dashboard/agent-prompt'
    | '/dashboard/agent-scopes'
    | '/dashboard/agent-tokens'
    | '/dashboard/ai-agents'
    | '/dashboard/ai-knowledge'
    | '/dashboard/audit-logs'
    | '/dashboard/calendar'
    | '/dashboard/commissions'
    | '/dashboard/contracts'
    | '/dashboard/dev-history'
    | '/dashboard/dev-todos'
    | '/dashboard/error-logs'
    | '/dashboard/feature-requests'
    | '/dashboard/fund'
    | '/dashboard/invitations'
    | '/dashboard/invoices'
    | '/dashboard/issue-reports'
    | '/dashboard/lookups'
    | '/dashboard/members'
    | '/dashboard/menu-management'
    | '/dashboard/opportunities'
    | '/dashboard/payments'
    | '/dashboard/profile'
    | '/dashboard/project-board'
    | '/dashboard/project-dashboard'
    | '/dashboard/quotes'
    | '/dashboard/receivables'
    | '/dashboard/renewals'
    | '/dashboard/reports'
    | '/dashboard/role-permissions'
    | '/dashboard/service-tickets'
    | '/dashboard/system-config'
    | '/dashboard/system-docs'
    | '/dashboard/tasks'
    | '/dashboard/user-manual'
    | '/dashboard/users'
    | '/dashboard/workspace'
    | '/dashboard/'
    | '/dashboard/cases/$caseId'
    | '/dashboard/clients/$clientId'
    | '/dashboard/ledger/clients'
    | '/dashboard/ledger/contracts'
    | '/dashboard/ledger/systems'
    | '/dashboard/cases/'
    | '/dashboard/ledger/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard/activity-logs'
    | '/dashboard/agent-activity'
    | '/dashboard/agent-audit'
    | '/dashboard/agent-prompt'
    | '/dashboard/agent-scopes'
    | '/dashboard/agent-tokens'
    | '/dashboard/ai-agents'
    | '/dashboard/ai-knowledge'
    | '/dashboard/audit-logs'
    | '/dashboard/calendar'
    | '/dashboard/commissions'
    | '/dashboard/contracts'
    | '/dashboard/dev-history'
    | '/dashboard/dev-todos'
    | '/dashboard/error-logs'
    | '/dashboard/feature-requests'
    | '/dashboard/fund'
    | '/dashboard/invitations'
    | '/dashboard/invoices'
    | '/dashboard/issue-reports'
    | '/dashboard/lookups'
    | '/dashboard/members'
    | '/dashboard/menu-management'
    | '/dashboard/opportunities'
    | '/dashboard/payments'
    | '/dashboard/profile'
    | '/dashboard/project-board'
    | '/dashboard/project-dashboard'
    | '/dashboard/quotes'
    | '/dashboard/receivables'
    | '/dashboard/renewals'
    | '/dashboard/reports'
    | '/dashboard/role-permissions'
    | '/dashboard/service-tickets'
    | '/dashboard/system-config'
    | '/dashboard/system-docs'
    | '/dashboard/tasks'
    | '/dashboard/user-manual'
    | '/dashboard/users'
    | '/dashboard/workspace'
    | '/dashboard'
    | '/dashboard/cases/$caseId'
    | '/dashboard/clients/$clientId'
    | '/dashboard/ledger/clients'
    | '/dashboard/ledger/contracts'
    | '/dashboard/ledger/systems'
    | '/dashboard/cases'
    | '/dashboard/ledger'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/dashboard/activity-logs'
    | '/dashboard/agent-activity'
    | '/dashboard/agent-audit'
    | '/dashboard/agent-prompt'
    | '/dashboard/agent-scopes'
    | '/dashboard/agent-tokens'
    | '/dashboard/ai-agents'
    | '/dashboard/ai-knowledge'
    | '/dashboard/audit-logs'
    | '/dashboard/calendar'
    | '/dashboard/commissions'
    | '/dashboard/contracts'
    | '/dashboard/dev-history'
    | '/dashboard/dev-todos'
    | '/dashboard/error-logs'
    | '/dashboard/feature-requests'
    | '/dashboard/fund'
    | '/dashboard/invitations'
    | '/dashboard/invoices'
    | '/dashboard/issue-reports'
    | '/dashboard/lookups'
    | '/dashboard/members'
    | '/dashboard/menu-management'
    | '/dashboard/opportunities'
    | '/dashboard/payments'
    | '/dashboard/profile'
    | '/dashboard/project-board'
    | '/dashboard/project-dashboard'
    | '/dashboard/quotes'
    | '/dashboard/receivables'
    | '/dashboard/renewals'
    | '/dashboard/reports'
    | '/dashboard/role-permissions'
    | '/dashboard/service-tickets'
    | '/dashboard/system-config'
    | '/dashboard/system-docs'
    | '/dashboard/tasks'
    | '/dashboard/user-manual'
    | '/dashboard/users'
    | '/dashboard/workspace'
    | '/dashboard/'
    | '/dashboard/cases/$caseId'
    | '/dashboard/clients/$clientId'
    | '/dashboard/ledger/clients'
    | '/dashboard/ledger/contracts'
    | '/dashboard/ledger/systems'
    | '/dashboard/cases/'
    | '/dashboard/ledger/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/workspace': {
      id: '/dashboard/workspace'
      path: '/workspace'
      fullPath: '/dashboard/workspace'
      preLoaderRoute: typeof DashboardWorkspaceRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/users': {
      id: '/dashboard/users'
      path: '/users'
      fullPath: '/dashboard/users'
      preLoaderRoute: typeof DashboardUsersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/user-manual': {
      id: '/dashboard/user-manual'
      path: '/user-manual'
      fullPath: '/dashboard/user-manual'
      preLoaderRoute: typeof DashboardUserManualRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/tasks': {
      id: '/dashboard/tasks'
      path: '/tasks'
      fullPath: '/dashboard/tasks'
      preLoaderRoute: typeof DashboardTasksRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/system-docs': {
      id: '/dashboard/system-docs'
      path: '/system-docs'
      fullPath: '/dashboard/system-docs'
      preLoaderRoute: typeof DashboardSystemDocsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/system-config': {
      id: '/dashboard/system-config'
      path: '/system-config'
      fullPath: '/dashboard/system-config'
      preLoaderRoute: typeof DashboardSystemConfigRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/service-tickets': {
      id: '/dashboard/service-tickets'
      path: '/service-tickets'
      fullPath: '/dashboard/service-tickets'
      preLoaderRoute: typeof DashboardServiceTicketsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/role-permissions': {
      id: '/dashboard/role-permissions'
      path: '/role-permissions'
      fullPath: '/dashboard/role-permissions'
      preLoaderRoute: typeof DashboardRolePermissionsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/reports': {
      id: '/dashboard/reports'
      path: '/reports'
      fullPath: '/dashboard/reports'
      preLoaderRoute: typeof DashboardReportsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/renewals': {
      id: '/dashboard/renewals'
      path: '/renewals'
      fullPath: '/dashboard/renewals'
      preLoaderRoute: typeof DashboardRenewalsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/receivables': {
      id: '/dashboard/receivables'
      path: '/receivables'
      fullPath: '/dashboard/receivables'
      preLoaderRoute: typeof DashboardReceivablesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/quotes': {
      id: '/dashboard/quotes'
      path: '/quotes'
      fullPath: '/dashboard/quotes'
      preLoaderRoute: typeof DashboardQuotesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/project-dashboard': {
      id: '/dashboard/project-dashboard'
      path: '/project-dashboard'
      fullPath: '/dashboard/project-dashboard'
      preLoaderRoute: typeof DashboardProjectDashboardRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/project-board': {
      id: '/dashboard/project-board'
      path: '/project-board'
      fullPath: '/dashboard/project-board'
      preLoaderRoute: typeof DashboardProjectBoardRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/profile': {
      id: '/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/payments': {
      id: '/dashboard/payments'
      path: '/payments'
      fullPath: '/dashboard/payments'
      preLoaderRoute: typeof DashboardPaymentsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/opportunities': {
      id: '/dashboard/opportunities'
      path: '/opportunities'
      fullPath: '/dashboard/opportunities'
      preLoaderRoute: typeof DashboardOpportunitiesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/menu-management': {
      id: '/dashboard/menu-management'
      path: '/menu-management'
      fullPath: '/dashboard/menu-management'
      preLoaderRoute: typeof DashboardMenuManagementRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/members': {
      id: '/dashboard/members'
      path: '/members'
      fullPath: '/dashboard/members'
      preLoaderRoute: typeof DashboardMembersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/lookups': {
      id: '/dashboard/lookups'
      path: '/lookups'
      fullPath: '/dashboard/lookups'
      preLoaderRoute: typeof DashboardLookupsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/issue-reports': {
      id: '/dashboard/issue-reports'
      path: '/issue-reports'
      fullPath: '/dashboard/issue-reports'
      preLoaderRoute: typeof DashboardIssueReportsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/invoices': {
      id: '/dashboard/invoices'
      path: '/invoices'
      fullPath: '/dashboard/invoices'
      preLoaderRoute: typeof DashboardInvoicesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/invitations': {
      id: '/dashboard/invitations'
      path: '/invitations'
      fullPath: '/dashboard/invitations'
      preLoaderRoute: typeof DashboardInvitationsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/fund': {
      id: '/dashboard/fund'
      path: '/fund'
      fullPath: '/dashboard/fund'
      preLoaderRoute: typeof DashboardFundRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/feature-requests': {
      id: '/dashboard/feature-requests'
      path: '/feature-requests'
      fullPath: '/dashboard/feature-requests'
      preLoaderRoute: typeof DashboardFeatureRequestsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/error-logs': {
      id: '/dashboard/error-logs'
      path: '/error-logs'
      fullPath: '/dashboard/error-logs'
      preLoaderRoute: typeof DashboardErrorLogsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/dev-todos': {
      id: '/dashboard/dev-todos'
      path: '/dev-todos'
      fullPath: '/dashboard/dev-todos'
      preLoaderRoute: typeof DashboardDevTodosRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/dev-history': {
      id: '/dashboard/dev-history'
      path: '/dev-history'
      fullPath: '/dashboard/dev-history'
      preLoaderRoute: typeof DashboardDevHistoryRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/contracts': {
      id: '/dashboard/contracts'
      path: '/contracts'
      fullPath: '/dashboard/contracts'
      preLoaderRoute: typeof DashboardContractsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/commissions': {
      id: '/dashboard/commissions'
      path: '/commissions'
      fullPath: '/dashboard/commissions'
      preLoaderRoute: typeof DashboardCommissionsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/calendar': {
      id: '/dashboard/calendar'
      path: '/calendar'
      fullPath: '/dashboard/calendar'
      preLoaderRoute: typeof DashboardCalendarRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/audit-logs': {
      id: '/dashboard/audit-logs'
      path: '/audit-logs'
      fullPath: '/dashboard/audit-logs'
      preLoaderRoute: typeof DashboardAuditLogsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/ai-knowledge': {
      id: '/dashboard/ai-knowledge'
      path: '/ai-knowledge'
      fullPath: '/dashboard/ai-knowledge'
      preLoaderRoute: typeof DashboardAiKnowledgeRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/ai-agents': {
      id: '/dashboard/ai-agents'
      path: '/ai-agents'
      fullPath: '/dashboard/ai-agents'
      preLoaderRoute: typeof DashboardAiAgentsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/agent-tokens': {
      id: '/dashboard/agent-tokens'
      path: '/agent-tokens'
      fullPath: '/dashboard/agent-tokens'
      preLoaderRoute: typeof DashboardAgentTokensRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/agent-scopes': {
      id: '/dashboard/agent-scopes'
      path: '/agent-scopes'
      fullPath: '/dashboard/agent-scopes'
      preLoaderRoute: typeof DashboardAgentScopesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/agent-prompt': {
      id: '/dashboard/agent-prompt'
      path: '/agent-prompt'
      fullPath: '/dashboard/agent-prompt'
      preLoaderRoute: typeof DashboardAgentPromptRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/agent-audit': {
      id: '/dashboard/agent-audit'
      path: '/agent-audit'
      fullPath: '/dashboard/agent-audit'
      preLoaderRoute: typeof DashboardAgentAuditRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/agent-activity': {
      id: '/dashboard/agent-activity'
      path: '/agent-activity'
      fullPath: '/dashboard/agent-activity'
      preLoaderRoute: typeof DashboardAgentActivityRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/activity-logs': {
      id: '/dashboard/activity-logs'
      path: '/activity-logs'
      fullPath: '/dashboard/activity-logs'
      preLoaderRoute: typeof DashboardActivityLogsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/ledger/': {
      id: '/dashboard/ledger/'
      path: '/ledger'
      fullPath: '/dashboard/ledger/'
      preLoaderRoute: typeof DashboardLedgerIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/cases/': {
      id: '/dashboard/cases/'
      path: '/cases'
      fullPath: '/dashboard/cases/'
      preLoaderRoute: typeof DashboardCasesIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/ledger/systems': {
      id: '/dashboard/ledger/systems'
      path: '/ledger/systems'
      fullPath: '/dashboard/ledger/systems'
      preLoaderRoute: typeof DashboardLedgerSystemsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/ledger/contracts': {
      id: '/dashboard/ledger/contracts'
      path: '/ledger/contracts'
      fullPath: '/dashboard/ledger/contracts'
      preLoaderRoute: typeof DashboardLedgerContractsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/ledger/clients': {
      id: '/dashboard/ledger/clients'
      path: '/ledger/clients'
      fullPath: '/dashboard/ledger/clients'
      preLoaderRoute: typeof DashboardLedgerClientsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/clients/$clientId': {
      id: '/dashboard/clients/$clientId'
      path: '/clients/$clientId'
      fullPath: '/dashboard/clients/$clientId'
      preLoaderRoute: typeof DashboardClientsClientIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/cases/$caseId': {
      id: '/dashboard/cases/$caseId'
      path: '/cases/$caseId'
      fullPath: '/dashboard/cases/$caseId'
      preLoaderRoute: typeof DashboardCasesCaseIdRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardActivityLogsRoute: typeof DashboardActivityLogsRoute
  DashboardAgentActivityRoute: typeof DashboardAgentActivityRoute
  DashboardAgentAuditRoute: typeof DashboardAgentAuditRoute
  DashboardAgentPromptRoute: typeof DashboardAgentPromptRoute
  DashboardAgentScopesRoute: typeof DashboardAgentScopesRoute
  DashboardAgentTokensRoute: typeof DashboardAgentTokensRoute
  DashboardAiAgentsRoute: typeof DashboardAiAgentsRoute
  DashboardAiKnowledgeRoute: typeof DashboardAiKnowledgeRoute
  DashboardAuditLogsRoute: typeof DashboardAuditLogsRoute
  DashboardCalendarRoute: typeof DashboardCalendarRoute
  DashboardCommissionsRoute: typeof DashboardCommissionsRoute
  DashboardContractsRoute: typeof DashboardContractsRoute
  DashboardDevHistoryRoute: typeof DashboardDevHistoryRoute
  DashboardDevTodosRoute: typeof DashboardDevTodosRoute
  DashboardErrorLogsRoute: typeof DashboardErrorLogsRoute
  DashboardFeatureRequestsRoute: typeof DashboardFeatureRequestsRoute
  DashboardFundRoute: typeof DashboardFundRoute
  DashboardInvitationsRoute: typeof DashboardInvitationsRoute
  DashboardInvoicesRoute: typeof DashboardInvoicesRoute
  DashboardIssueReportsRoute: typeof DashboardIssueReportsRoute
  DashboardLookupsRoute: typeof DashboardLookupsRoute
  DashboardMembersRoute: typeof DashboardMembersRoute
  DashboardMenuManagementRoute: typeof DashboardMenuManagementRoute
  DashboardOpportunitiesRoute: typeof DashboardOpportunitiesRoute
  DashboardPaymentsRoute: typeof DashboardPaymentsRoute
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardProjectBoardRoute: typeof DashboardProjectBoardRoute
  DashboardProjectDashboardRoute: typeof DashboardProjectDashboardRoute
  DashboardQuotesRoute: typeof DashboardQuotesRoute
  DashboardReceivablesRoute: typeof DashboardReceivablesRoute
  DashboardRenewalsRoute: typeof DashboardRenewalsRoute
  DashboardReportsRoute: typeof DashboardReportsRoute
  DashboardRolePermissionsRoute: typeof DashboardRolePermissionsRoute
  DashboardServiceTicketsRoute: typeof DashboardServiceTicketsRoute
  DashboardSystemConfigRoute: typeof DashboardSystemConfigRoute
  DashboardSystemDocsRoute: typeof DashboardSystemDocsRoute
  DashboardTasksRoute: typeof DashboardTasksRoute
  DashboardUserManualRoute: typeof DashboardUserManualRoute
  DashboardUsersRoute: typeof DashboardUsersRoute
  DashboardWorkspaceRoute: typeof DashboardWorkspaceRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardCasesCaseIdRoute: typeof DashboardCasesCaseIdRoute
  DashboardClientsClientIdRoute: typeof DashboardClientsClientIdRoute
  DashboardLedgerClientsRoute: typeof DashboardLedgerClientsRoute
  DashboardLedgerContractsRoute: typeof DashboardLedgerContractsRoute
  DashboardLedgerSystemsRoute: typeof DashboardLedgerSystemsRoute
  DashboardCasesIndexRoute: typeof DashboardCasesIndexRoute
  DashboardLedgerIndexRoute: typeof DashboardLedgerIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardActivityLogsRoute: DashboardActivityLogsRoute,
  DashboardAgentActivityRoute: DashboardAgentActivityRoute,
  DashboardAgentAuditRoute: DashboardAgentAuditRoute,
  DashboardAgentPromptRoute: DashboardAgentPromptRoute,
  DashboardAgentScopesRoute: DashboardAgentScopesRoute,
  DashboardAgentTokensRoute: DashboardAgentTokensRoute,
  DashboardAiAgentsRoute: DashboardAiAgentsRoute,
  DashboardAiKnowledgeRoute: DashboardAiKnowledgeRoute,
  DashboardAuditLogsRoute: DashboardAuditLogsRoute,
  DashboardCalendarRoute: DashboardCalendarRoute,
  DashboardCommissionsRoute: DashboardCommissionsRoute,
  DashboardContractsRoute: DashboardContractsRoute,
  DashboardDevHistoryRoute: DashboardDevHistoryRoute,
  DashboardDevTodosRoute: DashboardDevTodosRoute,
  DashboardErrorLogsRoute: DashboardErrorLogsRoute,
  DashboardFeatureRequestsRoute: DashboardFeatureRequestsRoute,
  DashboardFundRoute: DashboardFundRoute,
  DashboardInvitationsRoute: DashboardInvitationsRoute,
  DashboardInvoicesRoute: DashboardInvoicesRoute,
  DashboardIssueReportsRoute: DashboardIssueReportsRoute,
  DashboardLookupsRoute: DashboardLookupsRoute,
  DashboardMembersRoute: DashboardMembersRoute,
  DashboardMenuManagementRoute: DashboardMenuManagementRoute,
  DashboardOpportunitiesRoute: DashboardOpportunitiesRoute,
  DashboardPaymentsRoute: DashboardPaymentsRoute,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardProjectBoardRoute: DashboardProjectBoardRoute,
  DashboardProjectDashboardRoute: DashboardProjectDashboardRoute,
  DashboardQuotesRoute: DashboardQuotesRoute,
  DashboardReceivablesRoute: DashboardReceivablesRoute,
  DashboardRenewalsRoute: DashboardRenewalsRoute,
  DashboardReportsRoute: DashboardReportsRoute,
  DashboardRolePermissionsRoute: DashboardRolePermissionsRoute,
  DashboardServiceTicketsRoute: DashboardServiceTicketsRoute,
  DashboardSystemConfigRoute: DashboardSystemConfigRoute,
  DashboardSystemDocsRoute: DashboardSystemDocsRoute,
  DashboardTasksRoute: DashboardTasksRoute,
  DashboardUserManualRoute: DashboardUserManualRoute,
  DashboardUsersRoute: DashboardUsersRoute,
  DashboardWorkspaceRoute: DashboardWorkspaceRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardCasesCaseIdRoute: DashboardCasesCaseIdRoute,
  DashboardClientsClientIdRoute: DashboardClientsClientIdRoute,
  DashboardLedgerClientsRoute: DashboardLedgerClientsRoute,
  DashboardLedgerContractsRoute: DashboardLedgerContractsRoute,
  DashboardLedgerSystemsRoute: DashboardLedgerSystemsRoute,
  DashboardCasesIndexRoute: DashboardCasesIndexRoute,
  DashboardLedgerIndexRoute: DashboardLedgerIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
